use carl;

DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (255) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户密码',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '用户信息表';

DROP TABLE IF EXISTS `t_user_role`;
CREATE TABLE `t_user_role` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`user_id` BIGINT (20) NOT NULL DEFAULT -1 COMMENT '用户id',
	`role_id` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '角色id',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '用户角色对应关系表';

DROP TABLE IF EXISTS `t_role`;
CREATE TABLE `t_role` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` BIGINT (20) NOT NULL DEFAULT -1 COMMENT '角色名',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '角色信息表';

DROP TABLE IF EXISTS `t_role_permission`;
CREATE TABLE `t_role_permission` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`role_id` BIGINT (20) NOT NULL DEFAULT -1 COMMENT '角色id',
    `permission_id` BIGINT (20) NOT NULL DEFAULT -1 COMMENT '权限id',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '角色权限对应表';

DROP TABLE IF EXISTS `t_permission`;
CREATE TABLE `t_permission` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (100) NOT NULL DEFAULT '' COMMENT '权限名',
    `url` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '权限对应URL',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变更时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '权限信息表';






